#!/usr/bin/env python3

import os
import sys
import helpers
from analyzer import Analyzer
from termcolor import colored

def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    user = sys.argv[1].strip("@")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    tweets = helpers.get_user_timeline(user, 50)
    
    if tweets == None:
        sys.exit("Error, unable to access user's tweets")
    
    analyzer = Analyzer(positives, negatives)
    
    # analyze tweet
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(score, "green"), colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), colored(tweet, "yellow"))

if __name__ == "__main__":
    main()

